enum TranslatedString {
  PLAYING_IN = 'playingIn',
  CHANNEL_NOT_TEXT = 'channelNotText',
  GAME_NOT_ACTIVE = 'gameNotActive',
  GAME_NOT_PLAYING = 'gameNotPlaying',
  YOUR_CARDS = 'yourCards',
  CANT_PLAY_CARD = 'cantPlayCard',
  NOT_YOUR_TURN = 'notYourTurn',
  CALL_UNO = 'callUno',
  TOOK_CARD_ALLREADY = 'tookCardAllready',
  NO_CARD_TAKEN_TO_SKIP = 'noCardTakenToSkip',
  CMD_TUTORIAL_DESC = 'cmdTutorialDesc',
  CMD_PING_MSG = 'cmdPingMsg',
  CMD_PING_DESC = 'cmdPingDesc',
  CMD_INVITE_DESC = 'cmdInviteDesc',
  CMD_ADMIN_DESC = 'cmdAdminDesc',
  CMD_ADMIN_GAMECHANNEL_DESC = 'cmdAdminGameChannelDesc',
  CMD_AMDIN_GAMECHANNEL_SELECT_DESC = 'cmdAdminGameChannelSelectDesc',
  GAMECHANNEL_UPDATE = 'gameChannelUpdate',
  GAME_CONTROLS_SEND_FAIL = 'gameControlsSendFail',
  ERR_BASE = 'errBase',
  CALL_UNO_BEFORE_PLAYING = 'callUnoBeforePlaying',
  GAME_STARTED_BY = 'gameStartedBy',
  PLAYERS = 'players',
  START = 'start',
  START_ON_FIRST_CARD = 'startOnFirstCard',
  PLACE_CARD = 'placeCard',
  CHOOSE = 'choose',
  DIDNT_CALL_UNO = 'didntCallUno',
  CONGRATS = 'congrats',
  YOU_WIN = 'youWin',
  DRAW_CARDS = 'drawCards',
  DRAW_CARDS_FOUR = 'drawCardsFour',
  NEED_TO_CALL_UNO = 'needToCallUno',
  CARDS_OUTDATED = 'cardsOutdated',
  GAME_GROUP_NAME = 'gameGroupName',
  ROLE_NOT_FOUND = 'roleNotFound',
  NOTIFY_ON = 'notifyOn',
  NOTIFY_OFF = 'notifyOff',
}
/*
const de: { [key in TranslatedString]: string } = {
  'playingIn': 'Du spielst gerade in {0}',
};
*/
const en: { [key in TranslatedString]: string } = {
  playingIn: 'You are currntly playing in <#{0}>',
  channelNotText: "The game channel should be a text-channel",
  gameNotActive: "this isn't an active game thread",
  gameNotPlaying: "You are not playing in this game",
  yourCards: "your cards:",
  cantPlayCard: "You can't play this card",
  notYourTurn: "It's not your turn",
  callUno: "<@{0}> called uno!",
  tookCardAllready: "You already took a card this round",
  noCardTakenToSkip: "You can't skip if you didn't take a card",
  cmdTutorialDesc: "This command will to get started with the bot!",
  cmdPingMsg: "Pong :partying_face: ({0}ms ping)",
  cmdPingDesc: "This command will show you the ping of the bot",
  cmdInviteDesc: "Get the invite link of the bot and server",
  gameChannelUpdate: "The game channel has been updated to <#{0}>",
  gameControlsSendFail: "Failed to send the game controls",
  cmdAdminDesc: "This command is for admins only.",
  cmdAdminGameChannelDesc: "Select the channel where games are played in.",
  cmdAdminGameChannelSelectDesc: "This channel will be used to play games",
  errBase: "An error accoured!",
  callUnoBeforePlaying: "Don't forget to call uno when you put down you second to last card.",
  gameStartedBy: "Game started by<@{0}>",
  players: "players",
  start: "start",
  startOnFirstCard: "when the first card is played",
  placeCard: "place a card",
  choose: "choose",
  didntCallUno: "You didn't call uno, so you get 2 cards",
  congrats: "Congrats {0}!",
  youWin: "You win!",
  drawCards: "<@{0}> you need to draw {1} cards. Do so by clicking :flower_playing_cards: \`hand cards\` or play a +2 card.",
  drawCardsFour: "<@{0}> you need to draw 4 cards. Do so by clicking :flower_playing_cards: \`hand cards\`.",
  needToCallUno: "You need to call uno",
  cardsOutdated: "Your cards are outdated, please use the latest message or update them by clicking :flower_playing_cards: \`hand cards\`!",
  gameGroupName: "{0}s table",
  roleNotFound: "The role couldn't be found",
  notifyOn: "Notifications are now on",
  notifyOff: "Notifications are now off",
};
const de: { [key in TranslatedString]: string } = {
  playingIn: 'Du spielst gerade in <#{0}>',
  channelNotText: "Der Spiel-Channel sollte ein Text-Channel sein",
  gameNotActive: "Dies ist kein aktiver Spiel-Thread",
  gameNotPlaying: "Du spielst in diesem Spiel nicht",
  yourCards: "Deine Karten:",
  cantPlayCard: "Du kannst diese Karte nicht spielen",
  notYourTurn: "Du bist nicht am Zug",
  callUno: "<@{0}> ruft UNO!",
  tookCardAllready: "Du hast bereits eine Karte gezogen",
  noCardTakenToSkip: "Du kannst nicht überspringen, wenn du noch keine Karte gezogen hast",
  cmdTutorialDesc: "Dieser Befehl hilft dir, dich mit dem Bot vertraut zu machen!",
  cmdPingMsg: "Pong :partying_face: ({0}ms ping)",
  cmdPingDesc: "Dieser Befehl zeigt dir den Ping des Bots an",
  cmdInviteDesc: "Erhalte den Bot- und Server-Link",
  gameChannelUpdate: "Der Spiel-Channel wurde zu <#{0}> aktualisiert",
  gameControlsSendFail: "Das Senden der Spiel-Steuerung ist fehlgeschlagen",
  cmdAdminDesc: "Dieser Befehl ist nur für Administratoren.",
  cmdAdminGameChannelDesc: "Wähle den Channel, in dem Spiele gespielt werden.",
  cmdAdminGameChannelSelectDesc: "Dieser Channel wird verwendet, um Spiele zu spielen",
  errBase: "Ein Fehler ist aufgetreten!",
  callUnoBeforePlaying: "Vergiss nicht, UNO zu rufen, wenn du deine vorletzte Karte ablegst.",
  gameStartedBy: "Spiel gestartet von {0}",
  players: "Spieler",
  start: "Start",
  startOnFirstCard: "wenn die erste Karte gespielt wird",
  placeCard: "Karte ablegen",
  choose: "gewünscht",
  didntCallUno: "Du hast nicht UNO gerufens, also bekommst du 2 Karten",
  congrats: "Herzlichen Glückwunsch {0}!",
  youWin: "Du gewinnst!",
  drawCards: "<@{0}> du musst {1} Karten ziehen. Ziehe diese durch Klicken auf :flower_playing_cards: \`Handkarten\` auf oder lege eine +2 Karte ab.",
  drawCardsFour: "<@{0}> du musst 4 Karten ziehen. Ziehe diese durch Klicken auf :flower_playing_cards: \`Handkarten\` auf.",
  needToCallUno: "Du musst UNO rufen",
  cardsOutdated: "Deine Karten sind veraltet, bitte benutze die neueste Nachricht oder aktualisiere sie durch Klicken auf :flower_playing_cards: \`Handkarten\`!",
  gameGroupName: "{0}s Spieltisch",
  roleNotFound: "Die Rolle konnte nicht gefunden werden",
  notifyOn: "Benachrichtigungen sind nun eingeschaltet",
  notifyOff: "Benachrichtigungen sind nun ausgeschaltet",
};

export const lang = de;